---
# tasks file for nginx
- name: Install nginx
  become: true
  apt:
    name: nginx
    state: present

- name: Ensure nginx is started
  become: true
  service:
    name: nginx
    state: started

- name: Copy over nginx config
  become: true
  blockinfile:
    path: /etc/nginx/nginx.conf
    block: "{{ lookup('file', 'nginx.conf') }}"
    insertafter: 'http {'

- name: Comment out sites-enabled line and validate nginx
  become: true
  replace:
    path: /etc/nginx/nginx.conf
    regexp: '(.*etc/nginx/sites-enabled.*)'
    replace: '# \1'
    validate: '/usr/sbin/nginx -c %s -t'

- name: Restart nginx
  become: true
  service:
    name: nginx
    state: restarted
