---
- name: update web, nfs and db servers
  hosts: webservers, nfs, db
  remote_user: ec2-user
  become: true
  become_user: root
  gather_facts: False
  tasks:
    - name: ensure wireshark is at the latest version
      yum:
        name: wireshark
        state: latest

- name: update LB server
  hosts: lb
  remote_user: ubuntu
  become: true
  become_user: root
  gather_facts: False
  tasks:
    - name: update apt repo
      apt:
        update_cache: no

    - name: ensure wireshark is at the latest version
      apt:
        name: wireshark
        state: latest

- name: Create directory and file on nfs, web, db and lb servers
  hosts: nfs, webservers, db, lb
  become: true
  become_user: root
  gather_facts: False
  tasks:
    - name: Create directory
      file:
        path: /home/test
        state: directory

    - name: Create file
      file:
        path: /home/test/testfile.txt
        state: touch
        mode: '0777'
