---
- hosts: all
- name: Include dynamic variables
  import_playbook: ../static-assignments/common.yml
  include: ../dynamic-assignments/env-vars.yml

- hosts: uat-webservers
- name: uat webservers
  import_playbook: ../static-assignments/uat-webservers.yml
